### PR TITLE
Migrate from Travis to GH actions

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Same as https://github.com/babel/babel/pull/12412

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I think this won't run in the repo until this PR is merged, but here is the result: https://github.com/nicolo-ribaudo/babel-polyfills/actions/runs/388513176

**Comment by ljharb** [comment]
It definitely should run, as-is - you’re using pull_request instead of pull_request_target.

**Comment by ljharb** [comment]
Are actions perhaps disabled on this repo?

**Comment by nicolo-ribaudo** [comment]
The actions are enabled in this repo, and GH is running them on those commits in my fork. It just doesn't report the status for this PR :thinking: 

Schermata da 2020-11-30 14-53-17

**Comment by nicolo-ribaudo** [comment]
I pushed the commits to this repo and it's running https://github.com/babel/babel-polyfills/tree/gh-actions :shrug:

**Review by JLHwung — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Pull request merged**
