### PR TITLE
Fix shim/polyfill terminology

### PR DESCRIPTION
**Pull request by ljharb**
This follows the terms used in the [es-shims API](https://github.com/es-shims/es-shim-api#api-contract).

### CODE REVIEW

**Comment by zloirock** [comment]
I don't like es-shims terminology. Please, don't use the term "shim" here.

**Comment by ljharb** [comment]
Can you elaborate on why not? The term "shim" is pretty universally used in the ecosystem, predating even the es5-shim.

**Comment by zloirock** [comment]
For a long time for almost all "polyfill" at first means self-installed polyfill with feature detection, "shim" is not a word usually used for that. I don't think that it's good to concentrate attention on it. Now it's a word that could confuse more than "polyfill".

**Comment by nicolo-ribaudo** [comment]
Can we use the terms "self-installing polyfill" and "pure polyfill", specifying each time where it's needed?

**Comment by ljharb** [comment]
Sure, I’m fine with that. Will update shortly.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Pull request merged**
